// web/tob/src/components/login/CaptchaWidget.jsx
import { forwardRef, useEffect, useImperativeHandle, useMemo, useState } from 'react';

function getAnswer(mode, { clicks, slideX, tileY, rotateAngle }) {
  if (mode === 'slide') {
    return { x: Math.round(slideX), y: Math.round(tileY) };
  }
  if (mode === 'rotate') {
    return { angle: Math.round(rotateAngle) };
  }
  return clicks;
}

function isReady(mode, { touched, clicks, dotNum }) {
  if (mode === 'slide' || mode === 'rotate') return touched;
  return dotNum > 0 && clicks.length === dotNum;
}

const CaptchaWidget = forwardRef(function CaptchaWidget(
  { challenge, onAnswerChange, onReadyChange },
  ref
) {
  const mode = challenge?.mode || 'click';
  const masterImage = challenge?.master_image || '';
  const thumbImage = challenge?.thumb_image || '';
  const dotNum = Number(challenge?.dot_num) || 0;
  const tileW = Number(challenge?.tile_width) || 0;
  const tileY = Number(challenge?.tile_y) || 0;
  const thumbSize = Number(challenge?.thumb_size) || 0;

  const [natural, setNatural] = useState({ w: 0, h: 0 });
  const [clicks, setClicks] = useState([]);
  const [slideX, setSlideX] = useState(0);
  const [rotateAngle, setRotateAngle] = useState(0);
  const [touched, setTouched] = useState(false);

  useEffect(() => {
    setNatural({ w: 0, h: 0 });
    setClicks([]);
    setSlideX(Number(challenge?.tile_x) || 0);
    setRotateAngle(0);
    setTouched(false);
  }, [challenge]);

  const slideMax = Math.max(0, (natural.w || 0) - tileW);
  const answer = useMemo(
    () => getAnswer(mode, { clicks, slideX, tileY, rotateAngle }),
    [mode, clicks, slideX, tileY, rotateAngle]
  );
  const ready = useMemo(
    () => isReady(mode, { touched, clicks, dotNum }),
    [mode, touched, clicks, dotNum]
  );

  useEffect(() => {
    onAnswerChange?.(answer);
  }, [answer, onAnswerChange]);

  useEffect(() => {
    onReadyChange?.(ready);
  }, [ready, onReadyChange]);

  useImperativeHandle(ref, () => ({
    clear() {
      setClicks([]);
      setSlideX(Number(challenge?.tile_x) || 0);
      setRotateAngle(0);
      setTouched(false);
    },
    isReady: () => ready,
    getAnswer: () => answer,
  }));

  const onMasterLoad = (ev) => {
    setNatural({
      w: ev.target.naturalWidth,
      h: ev.target.naturalHeight,
    });
  };

  const onClickMaster = (e) => {
    if (mode !== 'click' || !dotNum || clicks.length >= dotNum) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const scale = rect.width > 0 ? natural.w / rect.width : 1;
    const x = Math.round((e.clientX - rect.left) * scale);
    const y = Math.round((e.clientY - rect.top) * scale);
    setClicks((prev) => [...prev, { x, y }]);
    setTouched(true);
  };

  if (mode === 'click') {
    return (
      <div className="captcha-widget">
        {thumbImage ? (
          <div className="captcha-thumb-wrap">
            <img src={thumbImage} alt="提示" className="captcha-thumb" />
          </div>
        ) : null}
        {masterImage ? (
          <div className="captcha-master-wrap">
            <div className="captcha-master-inner">
              <img
                src={masterImage}
                alt="验证码"
                className="captcha-master"
                onLoad={onMasterLoad}
                onClick={onClickMaster}
              />
              {natural.w > 0
                ? clicks.map((p, i) => (
                    <span
                      key={`${p.x}-${p.y}-${i}`}
                      className="captcha-dot"
                      style={{
                        left: `${(p.x / natural.w) * 100}%`,
                        top: `${(p.y / natural.h) * 100}%`,
                      }}
                    >
                      {i + 1}
                    </span>
                  ))
                : null}
            </div>
          </div>
        ) : null}
        {dotNum > 0 ? (
          <p className="captcha-progress">
            {clicks.length} / {dotNum}
          </p>
        ) : null}
      </div>
    );
  }

  if (mode === 'slide') {
    return (
      <div className="captcha-widget">
        {masterImage ? (
          <div className="captcha-master-wrap">
            <div className="captcha-master-inner">
              <img
                src={masterImage}
                alt="验证码"
                className="captcha-master captcha-master-slide"
                onLoad={onMasterLoad}
              />
              {thumbImage ? (
                <img
                  src={thumbImage}
                  alt="拼图块"
                  className="captcha-slide-tile"
                  style={{
                    left: natural.w > 0 ? `${(slideX / natural.w) * 100}%` : '0',
                    top: natural.h > 0 ? `${(tileY / natural.h) * 100}%` : '0',
                    width: natural.w > 0 ? `${(tileW / natural.w) * 100}%` : 'auto',
                  }}
                />
              ) : null}
            </div>
          </div>
        ) : null}
        <div className="captcha-slider-wrap">
          <input
            type="range"
            className="captcha-slider"
            min={0}
            max={slideMax}
            value={slideX}
            onChange={(e) => {
              setSlideX(Number(e.target.value));
              setTouched(true);
            }}
          />
          <p className="captcha-hint">拖动滑块，将拼图移至正确位置</p>
        </div>
      </div>
    );
  }

  return (
    <div className="captcha-widget">
      {masterImage ? (
        <div className="captcha-master-wrap captcha-rotate-wrap">
          <div className="captcha-master-inner captcha-rotate-inner">
            <img
              src={masterImage}
              alt="验证码"
              className="captcha-master captcha-master-rotate"
              onLoad={onMasterLoad}
            />
            {thumbImage ? (
              <img
                src={thumbImage}
                alt="旋转块"
                className="captcha-rotate-thumb"
                style={{
                  width: natural.w > 0 && thumbSize > 0 ? `${(thumbSize / natural.w) * 100}%` : '50%',
                  transform: `translate(-50%, -50%) rotate(${rotateAngle}deg)`,
                }}
              />
            ) : null}
          </div>
        </div>
      ) : null}
      <div className="captcha-slider-wrap">
        <input
          type="range"
          className="captcha-slider"
          min={0}
          max={360}
          value={rotateAngle}
          onChange={(e) => {
            setRotateAngle(Number(e.target.value));
            setTouched(true);
          }}
        />
        <p className="captcha-hint">拖动滑块旋转图片至正确角度（{rotateAngle}°）</p>
      </div>
    </div>
  );
});

export default CaptchaWidget;

// web/vue/src/components/CaptchaWidget.vue
<template>
  <div class="flex flex-col" style="width: fit-content; max-width: 92vw">
    <!-- CLICK -->
    <template v-if="mode === 'click'">
      <div v-if="thumbImage" class="inline-flex items-center bg-gray-50 border rounded mb-2 px-2 py-1">
        <img :src="thumbImage" alt="thumb" style="display:block;max-height:52px" />
      </div>
      <div v-if="masterImage" class="flex items-center justify-center bg-gray-50 border rounded p-1.5">
        <div style="display:inline-block;line-height:0;position:relative">
          <img
            ref="clickImg"
            :src="masterImage"
            alt="captcha"
            style="border-radius:6px;cursor:crosshair;display:block;max-height:380px;max-width:100%;object-fit:contain"
            @load="onMasterLoad"
            @click="onClickMaster"
          />
          <span
            v-for="(p, i) in (natural.w > 0 ? clicks : [])"
            :key="i"
            class="flex items-center justify-center text-white font-bold"
            :style="dotStyle(p)"
          >{{ i + 1 }}</span>
        </div>
      </div>
    </template>

    <!-- SLIDE -->
    <template v-else-if="mode === 'slide'">
      <div v-if="masterImage" class="bg-gray-50 border rounded p-1.5">
        <div ref="slideWrap" style="display:inline-block;line-height:0;position:relative">
          <img :src="masterImage" alt="captcha" style="border-radius:6px;display:block;max-width:100%" @load="onMasterLoad" />
          <img
            v-if="thumbImage"
            :src="thumbImage"
            alt="tile"
            :style="tileStyle"
          />
        </div>
      </div>
      <div class="mt-3">
        <a-slider :min="0" :max="slideMax" v-model:value="slideX" :tip-formatter="null" />
        <div class="text-xs text-gray-500 text-center">{{ t('auth.login.captcha_slide_hint') }}</div>
      </div>
    </template>

    <!-- ROTATE -->
    <template v-else-if="mode === 'rotate'">
      <div v-if="masterImage" class="flex items-center justify-center bg-gray-50 border rounded p-2">
        <div style="position:relative;line-height:0">
          <img :src="masterImage" alt="captcha" style="border-radius:50%;display:block;max-width:100%" @load="onMasterLoad" />
          <img
            v-if="thumbImage"
            :src="thumbImage"
            alt="thumb"
            :style="rotateThumbStyle"
          />
        </div>
      </div>
      <div class="mt-3">
        <a-slider :min="0" :max="360" v-model:value="rotateAngle" :tip-formatter="(v) => v + '°'" />
        <div class="text-xs text-gray-500 text-center">{{ t('auth.login.captcha_rotate_hint') }}</div>
      </div>
    </template>
  </div>
</template>

<script setup>
import { ref, reactive, computed, watch } from 'vue';
import { useI18n } from 'vue-i18n';

const { t } = useI18n();

const props = defineProps({
  // challenge: { mode, master_image, thumb_image, dot_num, tile_x, tile_y, tile_width, tile_height, thumb_size }
  challenge: { type: Object, default: () => ({}) },
});
const emit = defineEmits(['update:answer', 'update:ready']);

const mode = computed(() => props.challenge?.mode || 'click');
const masterImage = computed(() => props.challenge?.master_image || '');
const thumbImage = computed(() => props.challenge?.thumb_image || '');
const dotNum = computed(() => Number(props.challenge?.dot_num) || 0);

const natural = reactive({ w: 0, h: 0 });
const displayW = ref(0);

// click
const clicks = ref([]);
// slide
const slideX = ref(0);
// rotate
const rotateAngle = ref(0);

function resetForChallenge() {
  natural.w = 0;
  natural.h = 0;
  clicks.value = [];
  slideX.value = Number(props.challenge?.tile_x) || 0;
  rotateAngle.value = 0;
}
watch(() => props.challenge, resetForChallenge, { immediate: true });

function onMasterLoad(ev) {
  natural.w = ev.target.naturalWidth;
  natural.h = ev.target.naturalHeight;
  displayW.value = ev.target.clientWidth || ev.target.naturalWidth;
}

// ---- click ----
function onClickMaster(e) {
  if (mode.value !== 'click') return;
  if (!dotNum.value || clicks.value.length >= dotNum.value) return;
  const rect = e.currentTarget.getBoundingClientRect();
  // Map displayed px back to natural px (image may be scaled by max-width).
  const scale = rect.width > 0 ? natural.w / rect.width : 1;
  const x = Math.round((e.clientX - rect.left) * scale);
  const y = Math.round((e.clientY - rect.top) * scale);
  clicks.value = [...clicks.value, { x, y }];
}
function dotStyle(p) {
  return {
    position: 'absolute', width: '22px', height: '22px', borderRadius: '50%',
    background: 'rgba(37,99,235,0.22)', border: '2px solid #2563eb', fontSize: '12px',
    left: (p.x / natural.w) * 100 + '%',
    top: (p.y / natural.h) * 100 + '%',
    transform: 'translate(-50%, -50%)',
  };
}

// ---- slide ----
const tileW = computed(() => Number(props.challenge?.tile_width) || 0);
const tileY = computed(() => Number(props.challenge?.tile_y) || 0);
const slideMax = computed(() => Math.max(0, (natural.w || 0) - tileW.value));
const tileStyle = computed(() => ({
  position: 'absolute',
  left: natural.w > 0 ? (slideX.value / natural.w) * 100 + '%' : '0',
  top: natural.h > 0 ? (tileY.value / natural.h) * 100 + '%' : '0',
  width: natural.w > 0 ? (tileW.value / natural.w) * 100 + '%' : 'auto',
  height: 'auto',
}));

// ---- rotate ----
const rotateThumbStyle = computed(() => {
  const sz = Number(props.challenge?.thumb_size) || 0;
  return {
    position: 'absolute',
    left: '50%',
    top: '50%',
    width: natural.w > 0 && sz > 0 ? (sz / natural.w) * 100 + '%' : '50%',
    transform: `translate(-50%, -50%) rotate(${rotateAngle.value}deg)`,
    borderRadius: '50%',
  };
});

// Emit answer + readiness for the active mode.
const answer = computed(() => {
  if (mode.value === 'slide') return { x: Math.round(slideX.value), y: Math.round(tileY.value) };
  if (mode.value === 'rotate') return { angle: Math.round(rotateAngle.value) };
  return clicks.value;
});
const ready = computed(() => {
  if (mode.value === 'slide') return slideX.value > 0;
  if (mode.value === 'rotate') return rotateAngle.value > 0;
  return dotNum.value > 0 && clicks.value.length === dotNum.value;
});

watch(answer, (v) => emit('update:answer', v), { immediate: true, deep: true });
watch(ready, (v) => emit('update:ready', v), { immediate: true });

function clear() {
  if (mode.value === 'click') clicks.value = [];
  else if (mode.value === 'slide') slideX.value = Number(props.challenge?.tile_x) || 0;
  else rotateAngle.value = 0;
}
defineExpose({ clear });
</script>
